[telegram]
token = "1495210700:AAGWidUP6L3qYdBUx6B5dCImPR-zrNp24RI"
workers = 1
admins = [957539786]
admins_only = false
maintenance_mode = false
persistent_temp_data = true

[sqlite]
filename = "stickersbot.sqlite"

[bot]
sourcecode = ""
issues = ""
